# Generated by Django 4.2.16 on 2025-01-03 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务商名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='服务商代码')),
                ('website', models.URLField(blank=True, verbose_name='官网')),
                ('tracking_url', models.URLField(blank=True, help_text='使用{tracking_no}作为跟踪号占位符', verbose_name='跟踪链接')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物流服务商',
                'verbose_name_plural': '物流服务商',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(blank=True, max_length=100, verbose_name='跟踪号')),
                ('status', models.CharField(choices=[('pending', '待发货'), ('shipped', '已发货'), ('delivered', '已送达'), ('returned', '已退回'), ('lost', '已丢失')], default='pending', max_length=20, verbose_name='包裹状态')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='重量(kg)')),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='长(cm)')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='宽(cm)')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='高(cm)')),
                ('items', models.JSONField(default=list, verbose_name='包裹物品')),
                ('shipping_label', models.FileField(blank=True, upload_to='shipping_labels/', verbose_name='面单文件')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('tracking_info', models.JSONField(default=list, verbose_name='跟踪信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '包裹',
                'verbose_name_plural': '包裹',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('code', models.CharField(max_length=50, verbose_name='服务代码')),
                ('description', models.TextField(blank=True, verbose_name='服务说明')),
                ('estimated_days', models.IntegerField(default=0, verbose_name='预计天数')),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基础费用')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.carrier', verbose_name='服务商')),
            ],
            options={
                'verbose_name': '物流服务',
                'verbose_name_plural': '物流服务',
                'ordering': ['carrier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackageStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('pending', '待发货'), ('shipped', '已发货'), ('delivered', '已送达'), ('returned', '已退回'), ('lost', '已丢失')], max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('pending', '待发货'), ('shipped', '已发货'), ('delivered', '已送达'), ('returned', '已退回'), ('lost', '已丢失')], max_length=20, verbose_name='新状态')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.package', verbose_name='包裹')),
            ],
            options={
                'verbose_name': '包裹状态记录',
                'verbose_name_plural': '包裹状态记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
