# Generated by Django 4.2.16 on 2025-01-03 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('storage', '0001_initial'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.service', verbose_name='物流服务'),
        ),
        migrations.AddField(
            model_name='package',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.warehouse', verbose_name='发货仓库'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('carrier', 'code')},
        ),
    ]
