# Generated by Django 4.2.16 on 2025-01-03 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=50, verbose_name='货区编码')),
                ('area_name', models.CharField(max_length=100, verbose_name='货区名称')),
                ('area_type', models.CharField(choices=[('normal', '普通区'), ('cold', '冷藏区'), ('frozen', '冷冻区'), ('dangerous', '危险品区')], default='normal', max_length=20, verbose_name='货区类型')),
                ('location_code', models.CharField(max_length=50, verbose_name='货位编码')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '货位',
                'verbose_name_plural': '货位',
                'ordering': ['warehouse', 'area_code', 'location_code'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='仓库地址')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_out_no', models.CharField(max_length=50, unique=True, verbose_name='出库单号')),
                ('source_type', models.CharField(choices=[('sale', '销售出库'), ('transfer', '调拨出库'), ('scrap', '报废出库'), ('other', '其他出库')], max_length=20, verbose_name='来源类型')),
                ('source_no', models.CharField(max_length=50, verbose_name='来源单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('operator', models.CharField(max_length=50, verbose_name='操作人')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.warehouse', verbose_name='出库仓库')),
            ],
            options={
                'verbose_name': '出库单',
                'verbose_name_plural': '出库单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成本')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.allocation', verbose_name='货位')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.sku', verbose_name='商品')),
                ('stock_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='storage.stockoutrecord', verbose_name='出库单')),
            ],
            options={
                'verbose_name': '出库单明细',
                'verbose_name_plural': '出库单明细',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_in_no', models.CharField(max_length=50, unique=True, verbose_name='入库单号')),
                ('source_type', models.CharField(choices=[('purchase', '采购入库'), ('transfer', '调拨入库'), ('return', '退货入库'), ('other', '其他入库')], max_length=20, verbose_name='来源类型')),
                ('source_no', models.CharField(max_length=50, verbose_name='来源单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('operator', models.CharField(max_length=50, verbose_name='操作人')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.warehouse', verbose_name='入库仓库')),
            ],
            options={
                'verbose_name': '入库单',
                'verbose_name_plural': '入库单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockInDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成本')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.allocation', verbose_name='货位')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.sku', verbose_name='商品')),
                ('stock_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='storage.stockinrecord', verbose_name='入库单')),
            ],
            options={
                'verbose_name': '入库单明细',
                'verbose_name_plural': '入库单明细',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='allocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.warehouse', verbose_name='仓库'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_num', models.IntegerField(default=0, verbose_name='库存数量')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.sku', verbose_name='商品')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.supplier', verbose_name='供应商')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'ordering': ['-updated_at'],
                'unique_together': {('warehouse', 'sku')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='allocation',
            unique_together={('warehouse', 'location_code')},
        ),
    ]
