# Generated by Django 4.2.16 on 2025-01-03 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工厂名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='工厂代码')),
                ('contact', models.CharField(max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工厂',
                'verbose_name_plural': '工厂列表',
                'db_table': 'manufacturing_factory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('order_type', models.CharField(choices=[('sample', '样品订单'), ('mass', '量产订单')], default='mass', max_length=20, verbose_name='订单类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待处理'), ('in_production', '生产中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='订单状态')),
                ('quantity', models.IntegerField(verbose_name='生产数量')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='预计完成日期')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='预计交货日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.factory', verbose_name='生产工厂')),
                ('follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='following_orders', to=settings.AUTH_USER_MODEL, verbose_name='跟单员')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.sku', verbose_name='产品SKU')),
            ],
            options={
                'verbose_name': '生产订单',
                'verbose_name_plural': '生产订单列表',
                'db_table': 'manufacturing_production_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(verbose_name='评审日期')),
                ('content', models.TextField(verbose_name='评审内容')),
                ('conclusion', models.CharField(max_length=50, verbose_name='评审结论')),
                ('attachments', models.JSONField(default=list, verbose_name='附件列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('production_order', models.ForeignKey(limit_choices_to={'order_type': 'sample'}, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.productionorder', verbose_name='生产订单')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='评审人')),
            ],
            options={
                'verbose_name': '样品评审',
                'verbose_name_plural': '样品评审列表',
                'db_table': 'manufacturing_sample_review',
                'ordering': ['-review_date'],
            },
        ),
    ]
